version: '3.4'

services:
  worker:
    build: 
      context: .
      dockerfile: message-processor/Dockerfile
    restart: always
    depends_on:
     - "rabbitmq"
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
  webapi:
    image: ${DOCKER_REGISTRY-}host
    build:
      context: .
      dockerfile: webapi/Dockerfile
    ports:
    - "81:80"
  