apiVersion: v1
kind: Namespace
metadata:
  name: simplek8sconfigmap-secret-envvars

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-map
  namespace: simplek8sconfigmap-secret-envvars
data:
  MySecret: bVlwQHNzdzByZA== # base 64 encoded value not really secret. 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: simplek8sconfigmap-secret-envvars
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapi
    spec:
      containers:
        - name: webapicontainer
          image: joymon/simplek8sconfigmap:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: MyEnvVarFromMySecret
              valueFrom:
               secretKeyRef:
                name: secret-map
                key: MySecret
---
apiVersion: v1
kind: Service
metadata:
  name: webapiservice
  namespace: simplek8sconfigmap-secret-envvars
  labels:
    app: weather-forecast
    service: webapi
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort : 80
      protocol: TCP
  selector:
    service: webapi
